package com.visioners.civic.complaint.model;

public enum ActionType {
    CREATED,
    ML_VALIDATED,
    ML_REJECTED,
    ROUTED_TO_BA,
    ROUTED_TO_DEPARTMENT,
    ASSIGNED,
    WORKER_RESOLVED,
    WORKER_REJECTED,
    OFFICER_APPROVED,
    OFFICER_REJECTED,
    USER_REOPEN,
    BA_DECISION_APPROVE,
    BA_DECISION_REJECT,
    FEEDBACK_SUBMITTED,
    COMMUNITY_SUPPORT_TOGGLED,
    COMMUNITY_COMMENT_ADDED, BA_REJECT_REOPEN, BA_ROUTED_REOPEN, BA_ROUTED_ML
}
